#!/usr/bin/env bash
# hooks/universal/session-end/write-baton.sh
#
# Fires on session end (limit hit, /checkpoint invoked, or process exit).
# Writes .workflow/state/baton.md so the next agent can resume cleanly.
#
# Implements Principle 6 (Surgical Honesty Across Tool Handoffs).

set -euo pipefail

BATON="${DEVOPS_BATON:-.workflow/state/baton.md}"
SESSION_ID="${DEVOPS_SESSION_ID:-unknown}"
TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

mkdir -p "$(dirname "$BATON")"

# Try to gather state from the session
LAST_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "no-git")
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
DIRTY_FILES=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ' || echo 0)

# Count verified claims from this session
PROOFS_DIR=".workflow/proofs"
VERIFIED_COUNT=0
UNVERIFIED_COUNT=0
if [[ -d "$PROOFS_DIR" ]]; then
    VERIFIED_COUNT=$(find "$PROOFS_DIR" -name "*.yml" -newer "$BATON" 2>/dev/null | wc -l | tr -d ' ' || echo 0)
fi

# Open blockers
BLOCKERS_FILE=".workflow/state/blockers.md"
OPEN_BLOCKERS=0
if [[ -f "$BLOCKERS_FILE" ]]; then
    OPEN_BLOCKERS=$(grep -c "^## Blocker" "$BLOCKERS_FILE" 2>/dev/null || echo 0)
fi

# Read the active mode and lifecycle
ACTIVE_MODE=$(cat .workflow/state/active-mode.txt 2>/dev/null || echo "brownfield")
LIFECYCLE=$(cat .workflow/state/lifecycle.txt 2>/dev/null || echo "build")

# Compose the baton
cat > "$BATON" <<EOF
# Baton — handoff document

> Written by session-end hook. Read by next session-start hook.
> The next agent (any tool) reads this and resumes from \`next_action\`.

**last_updated**: $TS
**session_id**: $SESSION_ID
**tool**: ${DEVOPS_TOOL:-unknown}
**lifecycle_phase**: $LIFECYCLE
**active_mode**: $ACTIVE_MODE

---

## Git state

- **Branch**: $CURRENT_BRANCH
- **HEAD**: $LAST_COMMIT
- **Uncommitted changes**: $DIRTY_FILES files

---

## Verified work this session

- **Verified claims**: $VERIFIED_COUNT
- See \`.workflow/proofs/\` for individual proof artifacts.
- See \`session-summary.md\` (generated by \`generate-summary.sh\`) for full
  human-reviewable details.

---

## Open blockers

- **Count**: $OPEN_BLOCKERS
$(if (( OPEN_BLOCKERS > 0 )); then echo "- See \`.workflow/state/blockers.md\` — these must be resolved before merging."; fi)

---

## Next action

<!-- The next agent reads THIS section first. Be specific. -->
<!-- Replace this placeholder with the literal next instruction. -->

$(cat .workflow/state/next-action.txt 2>/dev/null || echo "Continue from the open task in /specs/. Read the latest commit message and the most recent entries in .workflow/proofs/ to understand context.")

---

## Open questions for the user

<!-- Anything the agent couldn't resolve alone -->

$(cat .workflow/state/open-questions.txt 2>/dev/null || echo "(none)")

---

## Files modified this session

$(if [[ "$DIRTY_FILES" != "0" ]]; then
    echo "\`\`\`"
    git status --short 2>/dev/null
    echo "\`\`\`"
else
    echo "(no uncommitted changes; check git log for committed work)"
fi)

---

## Recently completed claims

$(if [[ -d "$PROOFS_DIR" ]]; then
    find "$PROOFS_DIR" -name "*.yml" -newer "$BATON" 2>/dev/null | head -10 | while read f; do
        echo "- \`$f\`"
    done
fi)

---

## Resume protocol

The next session should:

1. Read \`constitution/PRINCIPLES.md\`, \`ANTIPATTERNS.md\`, \`LOOP.md\`
2. Read this baton
3. Address any open blockers FIRST
4. Then proceed with \`next_action\` above
5. If anything in this baton is unclear, ask the user before proceeding
EOF

# Log
echo "{\"ts\":$(date -u +%s),\"event\":\"session_end\",\"session_id\":\"$SESSION_ID\",\"verified_claims\":$VERIFIED_COUNT,\"open_blockers\":$OPEN_BLOCKERS}" >> .workflow/state/events.jsonl

echo "✓ Baton written to $BATON"
echo "  Verified claims: $VERIFIED_COUNT"
echo "  Open blockers:   $OPEN_BLOCKERS"
echo "  Next agent will resume from 'next_action' section."

exit 0
