#!/usr/bin/env bash
# hooks/universal/pre-tool/external-content-boundary.sh
#
# Phase 2 Area C / REQ-C5 — pre-tool hook that catches unwrapped external
# content via HMAC verification.
#
# Protocol: Claude Code pre-tool hooks receive the tool call payload on
# stdin as JSON containing { "tool_name", "tool_input", ... }. This hook
# scans tool_input (and any string fields) for <external-content …>
# markers, re-computes HMAC-SHA256(session_key, body || source ||
# "untrusted=true") over each marker, and:
#   - missing hmac or hmac mismatch → halt (exit 1) + log event + blocker
#   - valid hmac → exit 0 (call proceeds); OTel attribute recorded by
#     downstream layer.
#
# session_key is read from .workflow/state/session-key (16-byte hex,
# generated by observability/external-content-boundary.ts and rotated by
# hooks/universal/session-end/rotate-session-key.sh per C.06).
#
# REQ-C5 explicit: heuristic detection of "external-looking content"
# (URLs, "Here's what I found:", base64 chunks) is NOT used — the
# cryptographic gate is the source of truth.
#
# AC-C5.1: missing-hmac marker → exit 1 + log + blocker.
# AC-C5.2: valid-hmac marker → exit 0.

set -euo pipefail

EVENTS_LOG=".workflow/state/events.jsonl"
BLOCKERS=".workflow/state/blockers.md"
SESSION_KEY_PATH=".workflow/state/session-key"

# Read all stdin into a variable (the tool call payload)
PAYLOAD="$(cat || true)"

# Fast-path: no external-content marker in the payload, allow the call.
if ! echo "${PAYLOAD}" | grep -q '<external-content '; then
  exit 0
fi

# If the session key file does not exist, this is itself a violation:
# something is presenting external-content markers without the boundary
# layer having been initialised. Halt.
if [ ! -f "${SESSION_KEY_PATH}" ]; then
  mkdir -p "$(dirname "${EVENTS_LOG}")"
  printf '{"ts":"%s","event":"external_content.no_session_key","detail":"marker present but session-key not initialised"}\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "${EVENTS_LOG}"
  echo "- $(date -u +%Y-%m-%dT%H:%M:%SZ) pre-tool boundary hook halted: external-content marker present but session-key missing" >> "${BLOCKERS}"
  echo "BLOCKED: external-content marker present but session-key not initialised; run the boundary layer to generate one" >&2
  exit 1
fi

# Delegate to Python for HMAC verification (Node would also work; Python is
# always available per DevOPs's hook conventions on Windows + POSIX).
RESULT=$(python3 - <<'PYEOF'
import sys, os, re, hmac, hashlib, json
from datetime import datetime, timezone

payload = sys.stdin.read() if not sys.stdin.isatty() else ""

# Marker pattern: <external-content untrusted="true" source="..." [hmac="..."]>BODY</external-content>
marker_re = re.compile(
    r'<external-content\s+untrusted="true"\s+source="([^"]+)"(?:\s+hmac="([^"]*)")?\s*>(.*?)</external-content>',
    re.DOTALL,
)

with open('.workflow/state/session-key', 'r') as f:
    key_hex = f.read().strip()
key = bytes.fromhex(key_hex)

now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
failures = []
matched = 0

for m in marker_re.finditer(payload):
    matched += 1
    source = m.group(1)
    provided_hmac = m.group(2) or ""
    body = m.group(3)
    if not provided_hmac:
        failures.append({
            "ts": now,
            "event": "external_content.missing_hmac",
            "source": source,
            "body_prefix": body[:40],
        })
        continue
    mac_input = (body + source + "untrusted=true").encode("utf-8")
    expected = hmac.new(key, mac_input, hashlib.sha256).digest()
    # base64-encode for comparison with the wrap()-emitted format
    import base64
    expected_b64 = base64.b64encode(expected).decode("ascii")
    if not hmac.compare_digest(expected_b64, provided_hmac):
        failures.append({
            "ts": now,
            "event": "external_content.hmac_mismatch",
            "source": source,
            "body_prefix": body[:40],
            "provided_hmac_prefix": provided_hmac[:16],
            "expected_hmac_prefix": expected_b64[:16],
        })

# Read raw payload from stdin a second time? No — we consumed it.
# Output JSON result for the bash caller.
print(json.dumps({"matched": matched, "failures": failures}))
PYEOF
)
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
  echo "BLOCKED: external-content boundary verifier failed to execute" >&2
  exit 1
fi

# Need to actually pipe PAYLOAD into the python script. Above heredoc consumed
# its stdin from the bash stdin which is empty. Redo with payload piped in.
RESULT=$(printf '%s' "${PAYLOAD}" | python3 - <<'PYEOF'
import sys, os, re, hmac, hashlib, json, base64
from datetime import datetime, timezone

payload = sys.stdin.read()

marker_re = re.compile(
    r'<external-content\s+untrusted="true"\s+source="([^"]+)"(?:\s+hmac="([^"]*)")?\s*>(.*?)</external-content>',
    re.DOTALL,
)

with open('.workflow/state/session-key', 'r') as f:
    key_hex = f.read().strip()
key = bytes.fromhex(key_hex)

now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
failures = []
matched = 0

for m in marker_re.finditer(payload):
    matched += 1
    source = m.group(1)
    provided_hmac = m.group(2) or ""
    body = m.group(3)
    if not provided_hmac:
        failures.append({
            "ts": now,
            "event": "external_content.missing_hmac",
            "source": source,
            "body_prefix": body[:40],
        })
        continue
    mac_input = (body + source + "untrusted=true").encode("utf-8")
    expected = hmac.new(key, mac_input, hashlib.sha256).digest()
    expected_b64 = base64.b64encode(expected).decode("ascii")
    if not hmac.compare_digest(expected_b64, provided_hmac):
        failures.append({
            "ts": now,
            "event": "external_content.hmac_mismatch",
            "source": source,
            "body_prefix": body[:40],
        })

print(json.dumps({"matched": matched, "failures": failures}))
PYEOF
)

# Parse result
MATCHED=$(echo "${RESULT}" | python3 -c "import json,sys;print(json.load(sys.stdin)['matched'])")
FAILURE_COUNT=$(echo "${RESULT}" | python3 -c "import json,sys;print(len(json.load(sys.stdin)['failures']))")

if [ "${FAILURE_COUNT}" -gt 0 ]; then
  mkdir -p "$(dirname "${EVENTS_LOG}")"
  # Emit each failure as a JSONL event
  echo "${RESULT}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for f in data['failures']:
    print(json.dumps(f))
" >> "${EVENTS_LOG}"
  echo "- $(date -u +%Y-%m-%dT%H:%M:%SZ) pre-tool boundary hook halted: ${FAILURE_COUNT} HMAC failure(s); see ${EVENTS_LOG}" >> "${BLOCKERS}"
  echo "BLOCKED: external-content boundary HMAC verification failed (${FAILURE_COUNT} of ${MATCHED} markers); see ${EVENTS_LOG}" >&2
  exit 1
fi

# All markers verified. The OTel attribute external_content.hmac_verified=true
# is the consumer's responsibility (DevOPs's OTel span manager).

# C.08 — REQ-C6 (AC-C6.1) gating: if a rebuff_block-confidence event was
# observed earlier in this session AND the current tool call is destructive
# (write, push, deploy, exec, db-mutate), require an unconsumed
# approval_token in approvals.jsonl.
#
# A "destructive" detection here is conservative: tool_name matching
# (Write, Edit, Bash with 'rm|push|deploy|drop|exec', etc.) — the calling
# harness is the authoritative gate; this hook adds the approval layer.

# Detect destructive intent from the PAYLOAD JSON (tool_name + tool_input)
IS_DESTRUCTIVE=$(python3 - <<'PYEOF'
import sys, json
try:
    data = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
except Exception:
    data = {}
tn = (data.get("tool_name") or "").lower()
ti = json.dumps(data.get("tool_input") or {}).lower()
destructive_tools = {"write", "edit", "multiedit", "notebookedit", "bash", "powershell"}
destructive_cmds = ["git push", "git reset --hard", "rm -rf", "drop table", "deploy", "kubectl delete", "terraform apply"]
if tn in destructive_tools and tn != "bash" and tn != "powershell":
    print("yes"); sys.exit(0)
if tn in {"bash", "powershell"}:
    if any(c in ti for c in destructive_cmds):
        print("yes"); sys.exit(0)
print("no")
PYEOF
 "${PAYLOAD}")

if [ "${IS_DESTRUCTIVE}" != "yes" ]; then
  # Non-destructive call; HMAC verification already passed above.
  exit 0
fi

# Destructive call: check if a rebuff_block event was observed in this
# session's events log AND no unconsumed approval_token covers it.
BLOCK_OBSERVED=$(grep -c '"rebuff_confidence_block"' "${EVENTS_LOG}" 2>/dev/null || echo 0)
BLOCK_OBSERVED=${BLOCK_OBSERVED:-0}
if [ "${BLOCK_OBSERVED}" -eq 0 ]; then
  # No prior block signal; destructive call proceeds.
  exit 0
fi

APPROVALS_PATH=".workflow/state/approvals.jsonl"
if [ ! -f "${APPROVALS_PATH}" ]; then
  echo "BLOCKED: rebuff confidence >= block threshold earlier this session and no approval in ${APPROVALS_PATH}; run: devops approve <claim-id> --rationale=\"...\"" >&2
  echo "- $(date -u +%Y-%m-%dT%H:%M:%SZ) destructive call blocked: missing approval after rebuff block" >> "${BLOCKERS}"
  exit 1
fi

# Look for an unconsumed approval entry with valid entry_hmac.
APPROVED=$(python3 - <<'PYEOF'
import sys, json, hmac, hashlib, base64
from datetime import datetime, timezone

approvals_path = ".workflow/state/approvals.jsonl"
sk_path = ".workflow/state/session-key"

with open(sk_path) as f:
    key = bytes.fromhex(f.read().strip())

lines = []
with open(approvals_path) as f:
    for ln in f:
        ln = ln.strip()
        if not ln: continue
        try:
            lines.append(json.loads(ln))
        except Exception:
            pass

now = datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')
consumed_index = None
for i, entry in enumerate(lines):
    if entry.get("consumed_at"):
        continue
    approver = entry.get("approver_identity", "")
    claim_id = entry.get("claim_id", "")
    token = entry.get("approval_token", "")
    stored_hmac = entry.get("entry_hmac", "")
    mac_input = (approver + claim_id + token).encode("utf-8")
    expected = base64.b64encode(hmac.new(key, mac_input, hashlib.sha256).digest()).decode("ascii")
    if hmac.compare_digest(expected, stored_hmac):
        consumed_index = i
        break

if consumed_index is None:
    print("no")
    sys.exit(0)

# Mark consumed and rewrite the file
lines[consumed_index]["consumed_at"] = now
with open(approvals_path, "w") as f:
    for entry in lines:
        f.write(json.dumps(entry) + "\n")
print("yes")
PYEOF
)

if [ "${APPROVED}" = "yes" ]; then
  # One-shot approval consumed; destructive call proceeds.
  exit 0
fi

echo "BLOCKED: destructive call after rebuff block requires unconsumed approval_token with valid entry_hmac; run: devops approve <claim-id> --rationale=\"...\"" >&2
echo "- $(date -u +%Y-%m-%dT%H:%M:%SZ) destructive call blocked: no matching unconsumed approval token" >> "${BLOCKERS}"
exit 1
